language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run coverage && codecov
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master